#!/usr/bin/env python3
"""Stage, commit, and push the day's changes."""
from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def parse_date(s) -> str:
    if not s or s == "today":
        return datetime.now(timezone(timedelta(hours=2))).strftime("%Y-%m-%d")
    return s


def run(cmd, check=True) -> subprocess.CompletedProcess:
    print(f"$ {' '.join(cmd)}")
    return subprocess.run(cmd, cwd=ROOT, check=check, capture_output=True, text=True)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--date", default="today")
    p.add_argument("--no-push", action="store_true")
    args = p.parse_args()

    date_str = parse_date(args.date)

    # 1. Sync with remote
    run(["git", "pull", "--rebase", "origin", "main"], check=False)

    # 2. Stage
    paths = [
        "data/news.db",
        "site/src/content/articles",
        "site/src/content/briefings",
        "site/public/audio",
        "daily",
    ]
    run(["git", "add", "--"] + paths)

    # 3. Diff check
    diff = run(["git", "diff", "--cached", "--stat"], check=False)
    if not diff.stdout.strip():
        print("ℹ️  nothing to commit")
        return
    print(diff.stdout)

    # 4. Commit
    msg = (
        f"📰 Daily briefing: {date_str}\n\n"
        f"Auto-generated by berlin-gastro-news pipeline.\n"
    )
    run(["git", "commit", "-m", msg])

    # 5. Push
    if args.no_push:
        print("ℹ️  --no-push, stopping after commit")
        return
    push = run(["git", "push", "origin", "main"], check=False)
    print(push.stdout)
    if push.returncode != 0:
        print(push.stderr, file=sys.stderr)
        sys.exit(push.returncode)
    print(f"✅ pushed {date_str}")


if __name__ == "__main__":
    main()
